<a href="https://colab.research.google.com/github/Ginko2501/SURP2022/blob/main/solve_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import csv
import math
import numpy as np

In [21]:
a = np.array([1,2])
b = np.array([1,2])
print(a)
np.concatenate((a,b),axis=0)

[1 2]


array([1, 2, 1, 2])

In [24]:
def solve_matrix (v1, v2, w1, w2):
  vec = np.concatenate((v2,w2), axis=0)
  mat = np.array([ [v1[0], v1[1], 0,   0  ],
            [0,   0,   v1[0], v1[1]], 
            [w1[0], w1[1], 0,  0,  ],
            [0,   0,   w1[0], w1[1]], ])
  return np.linalg.solve(mat,vec)

In [25]:
v1 = np.array([-1,1])
v2 = np.array([-1,1])
w1 = np.array([0,1])
w2 = np.array([1,0])
solve_matrix(v1,v2,w1,w2)

[-1  1  1  0]
[[-1  1  0  0]
 [ 0  0 -1  1]
 [ 0  1  0  0]
 [ 0  0  0  1]]


array([ 2.,  1., -1.,  0.])